# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sesh < Formula
  desc "Unified session browser for coding agents"
  homepage "https://github.com/dru89/sesh"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dru89/sesh/releases/download/v0.9.1/sesh_0.9.1_darwin_amd64.tar.gz"
      sha256 "6638d00c4777fb2c322ac7c56abba2dcc9995389ab0a3284ef8a9c4b3b5039f3"

      define_method(:install) do
        bin.install "sesh"
        bash_completion.install "shell/sesh.bash" => "sesh"
        zsh_completion.install "shell/sesh.zsh" => "_sesh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dru89/sesh/releases/download/v0.9.1/sesh_0.9.1_darwin_arm64.tar.gz"
      sha256 "619567158eafd71e8f312f8c53f86ef3e9c121b37a9ffa2480ad7d4707845591"

      define_method(:install) do
        bin.install "sesh"
        bash_completion.install "shell/sesh.bash" => "sesh"
        zsh_completion.install "shell/sesh.zsh" => "_sesh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dru89/sesh/releases/download/v0.9.1/sesh_0.9.1_linux_amd64.tar.gz"
      sha256 "b38ca79e3f43a47b0af7c1531fc0a5995bc8b3503b65b3b7df8689189f59f342"
      define_method(:install) do
        bin.install "sesh"
        bash_completion.install "shell/sesh.bash" => "sesh"
        zsh_completion.install "shell/sesh.zsh" => "_sesh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dru89/sesh/releases/download/v0.9.1/sesh_0.9.1_linux_arm64.tar.gz"
      sha256 "65210c3eabe72038800cda27f26073b30494d8987388476db2d10b5a00761f4f"
      define_method(:install) do
        bin.install "sesh"
        bash_completion.install "shell/sesh.bash" => "sesh"
        zsh_completion.install "shell/sesh.zsh" => "_sesh"
      end
    end
  end

  test do
    system "#{bin}/sesh", "version"
  end
end
