# This file was generated by GoReleaser. DO NOT EDIT.
cask "sesh" do
  version "2.2.0"

  on_macos do
    on_intel do
      sha256 "b63fb0638e86890e07bfb78e269fd6b3a90e5129acc4c893414475f00e9f9f30"
      url "https://github.com/dru89/sesh/releases/download/v#{version}/sesh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8fd939c5a40ac737c4b3516e972016da4e6d219ed41fab0fee4f12b161403dfa"
      url "https://github.com/dru89/sesh/releases/download/v#{version}/sesh_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b5f556dd4a7221423a6aab5074dd6e7a5663a20bd19378c50e24439e4a1b8256"
      url "https://github.com/dru89/sesh/releases/download/v#{version}/sesh_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "35ecb99bd2491781735ef8faab43fe8da52040b3f3835d39a434839c49cf7675"
      url "https://github.com/dru89/sesh/releases/download/v#{version}/sesh_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sesh"
  desc "Unified session browser for coding agents"
  homepage "https://github.com/dru89/sesh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sesh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sesh"]
    end
  end

  # No zap stanza required

end
