# This file was generated by GoReleaser. DO NOT EDIT.
cask "sesh" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/dru89/sesh/releases/download/v#{version}/sesh_#{version}_darwin_amd64.tar.gz"
      sha256 "39ab073c0b04e92bdfde82f0e8f9f89e41457504002f21d338be3cb77f05a0f9"
    end
    on_arm do
      url "https://github.com/dru89/sesh/releases/download/v#{version}/sesh_#{version}_darwin_arm64.tar.gz"
      sha256 "b6884866c62acf92cb06bf874026b7caa355023b92cd31b3fc6a350ce6c79f61"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dru89/sesh/releases/download/v#{version}/sesh_#{version}_linux_amd64.tar.gz"
      sha256 "ea0cb83d41800442ee79a3477b2ebaf1808553b19c360a9c28c664336bed7554"
    end
    on_arm do
      url "https://github.com/dru89/sesh/releases/download/v#{version}/sesh_#{version}_linux_arm64.tar.gz"
      sha256 "42fc3439f03d4f0d68ed5bc647dbd411527248bd30c58afac458fccc73582f46"
    end
  end

  name "sesh"
  desc "Unified session browser for coding agents"
  homepage "https://github.com/dru89/sesh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sesh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sesh"]
    end
  end

  # No zap stanza required

end
