# This file was generated by GoReleaser. DO NOT EDIT.
cask "sesh" do
  version "0.11.0"

  on_macos do
    on_intel do
      url "https://github.com/dru89/sesh/releases/download/v#{version}/sesh_#{version}_darwin_amd64.tar.gz"
      sha256 "893286ef6d071648d4cc67b4ed9f5ec2e6bc0c0cec40b2cd8d659408b26681f3"
    end
    on_arm do
      url "https://github.com/dru89/sesh/releases/download/v#{version}/sesh_#{version}_darwin_arm64.tar.gz"
      sha256 "665cb49e034146aca26d31633eb13b67eb24ec4db2ea6df9f85906807e564c82"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dru89/sesh/releases/download/v#{version}/sesh_#{version}_linux_amd64.tar.gz"
      sha256 "5a08897abf08f6a95235c0764e515097943a7b6302f91181399c450176e0e7df"
    end
    on_arm do
      url "https://github.com/dru89/sesh/releases/download/v#{version}/sesh_#{version}_linux_arm64.tar.gz"
      sha256 "4fae3cabc7a7acd64a25d14b0b4d64299389d9fc66d0dc1fe7124208ce7d9f0c"
    end
  end

  name "sesh"
  desc "Unified session browser for coding agents"
  homepage "https://github.com/dru89/sesh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sesh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sesh"]
    end
  end

  # No zap stanza required

end
